
#
# SERVER
#
server:
  port: 80
#  ssl:
#    bundle: server
#    key-store-type: PKCS12
#
# SPRING
#
spring:
  application:
    name: news
#  ssl:
#    bundle:
#      pem:
#        server:
#          keystore:
#            type: PKCS12
#            certificate: classpath:server.crt
#            private-key: server.key
#            private-key-password: ${ssl.private-key-password}
  config:
    import: classpath:env.yml
#
# INTEGRATION
#
newsapi:
  apikey: ${newsapi.apikey}